---
# tasks file for linux_unreachable_host_check
- name: Starting Playbook.
  block:
  - name: Gathering Facts
    setup:
      gather_subset: "min,hardware,network"

  - name: Successfull Pinged hosts uptime.
    debug:
      msg: "{{ (ansible_uptime_seconds/60/60/24) | int }}"

  rescue:
  - name: Host was not rechable hence sending mail.
    mail:
      host: smtp.gmail.com
      port: 587
      username: ansiblelearning4@gmail.com
      password: "{{ my_password }}"
      subject: "Host Unrechable {{ inventory_hostname }} Needs Attention -- Ansible Report"
      body: "Ansible Report"
      to: 'ansiblelearning4@gmail.com'
    delegate_to: localhost

